#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.xdd.entity
  mapperLocations: classpath:mapper/*.xml


#开发环境配置
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/dev
    username: niuhaitao
    password: 880607
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    
#测试环境配置
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: niuhaitao
    password: 880607
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    
    
#生产环境配置
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://localhost:3306/prod
    username: niuhaitao
    password: 880607
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource