package com.pisces.web.config;

public enum WebMessage {
	UNKNOWN,
	CREATE,
	INSERT,
	UPDATE,
	DELETE,
	SELECT,
	INCORRECT_PARMS,
	CODE_NOT_NULL,
	CODE_NOT_REPEAT,
	NULL_POINTER_EXCEPTION,
	SERVER_ERROR,
	DB_ERROR,
	NOT_NEW_REQUEST,
	NOT_EXISTED,
	EXISTED,
	INVALIDATION_ENTITY_PROPERTY
}
